store_names = [
    "Leicester Square",
    "London Stratford",
    "Bluewater",
    "Westfield",
    "Battersea",
    "Legoland Windsor",
    "Briston",
    "Cardiff",
    "Southampton West Quay",
    "Brighton",
    "Milton Keynes",
    "Birmingham",
    "Manchester Trafford Centre",
    "Manchester Arndale",
    "Liverpool",
    "Sheffield Meadowhall",
    "Leeds",
    "Metrocentre Newcastle",
    "Glasgow",
    "Edinburgh",
]